package nginx

// **Validates: Requirements 6.2, 6.3**
//
// Property 13: Vessel deployment comment round-trip
//
// For any deployment name string, CreateSiteForDeployment must produce a
// config file whose first line is exactly "# vessel-deployment: <name>", and
// extractVesselDeployment applied to that content must return the original
// deployment name unchanged.

import (
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"testing/quick"
	"unicode"
)

// generateDeploymentName returns a random deployment name string that may
// include letters, digits, hyphens, underscores, spaces, and a selection of
// special characters. The name is guaranteed to be non-empty and must not
// contain a newline (which would break the single-line comment format).
func generateDeploymentName(rng *rand.Rand) string {
	// Character pools for varied deployment names.
	pools := []string{
		"abcdefghijklmnopqrstuvwxyz",
		"ABCDEFGHIJKLMNOPQRSTUVWXYZ",
		"0123456789",
		"-_. ",
		"!@#$%^&*()+=[]{}|;',.<>?/~`",
	}

	// Pick a length between 1 and 60.
	length := 1 + rng.Intn(60)
	var sb strings.Builder
	for i := 0; i < length; i++ {
		pool := pools[rng.Intn(len(pools))]
		ch := pool[rng.Intn(len(pool))]
		// Skip newlines and carriage returns — they would break the comment line.
		if ch == '\n' || ch == '\r' {
			ch = 'x'
		}
		sb.WriteByte(ch)
	}
	name := sb.String()

	// Trim leading/trailing whitespace: extractVesselDeployment trims the
	// extracted value, so a name with leading/trailing whitespace would not
	// round-trip correctly. The property only holds for trimmed names.
	name = strings.TrimSpace(name)

	// Ensure the name is not empty after trimming (TrimSpace on an
	// all-whitespace string yields ""). Replace with a safe default.
	if name == "" {
		name = fmt.Sprintf("deployment-%d", rng.Int63())
	}

	return name
}

// TestVesselDeploymentCommentRoundTripProperty verifies Property 13:
//
// For any deployment name string, CreateSiteForDeployment must produce a
// config file whose first line is exactly "# vessel-deployment: <name>", and
// extractVesselDeployment applied to that content must return the original
// deployment name unchanged.
//
// Runs a minimum of 100 iterations with random deployment names including
// names with spaces, special characters, and mixed case.
//
// **Validates: Requirements 6.2, 6.3**
func TestVesselDeploymentCommentRoundTripProperty(t *testing.T) {
	// Set up a temporary nginx config root with a sites-available directory.
	tmpDir := t.TempDir()
	sitesAvailable := filepath.Join(tmpDir, "sites-available")
	if err := os.MkdirAll(sitesAvailable, 0755); err != nil {
		t.Fatalf("failed to create sites-available: %v", err)
	}
	m := &Manager{configRoot: tmpDir}

	rng := rand.New(rand.NewSource(42)) //nolint:gosec // deterministic seed for reproducibility
	const iterations = 20

	for i := 0; i < iterations; i++ {
		deploymentName := generateDeploymentName(rng)
		siteName := fmt.Sprintf("site-%d", i)

		// CreateSiteForDeployment must succeed.
		err := m.CreateSiteForDeployment(siteName, "example.com", 8080, "", deploymentName)
		if err != nil {
			t.Errorf("iteration %d: CreateSiteForDeployment(%q) returned error: %v", i, deploymentName, err)
			continue
		}

		// Read the written file.
		data, err := os.ReadFile(filepath.Join(sitesAvailable, siteName))
		if err != nil {
			t.Errorf("iteration %d: failed to read site file for deployment %q: %v", i, deploymentName, err)
			continue
		}
		content := string(data)

		// Property A: the first line must be exactly "# vessel-deployment: <name>".
		expectedFirstLine := "# vessel-deployment: " + deploymentName
		lines := strings.SplitN(content, "\n", 2)
		if lines[0] != expectedFirstLine {
			t.Errorf("iteration %d: first line = %q, want %q (deployment name: %q)",
				i, lines[0], expectedFirstLine, deploymentName)
		}

		// Property B: extractVesselDeployment must return the original name unchanged.
		extracted := extractVesselDeployment(content)
		if extracted != deploymentName {
			t.Errorf("iteration %d: extractVesselDeployment = %q, want %q (round-trip failed)",
				i, extracted, deploymentName)
		}
	}
}

// TestVesselDeploymentCommentFirstLineProperty uses testing/quick to verify
// that for any deployment name (generated by the quick framework), the first
// line of the config produced by CreateSiteForDeployment is always exactly
// "# vessel-deployment: <name>".
//
// **Validates: Requirements 6.3**
func TestVesselDeploymentCommentFirstLineProperty(t *testing.T) {
	tmpDir := t.TempDir()
	sitesAvailable := filepath.Join(tmpDir, "sites-available")
	if err := os.MkdirAll(sitesAvailable, 0755); err != nil {
		t.Fatalf("failed to create sites-available: %v", err)
	}
	m := &Manager{configRoot: tmpDir}

	counter := 0

	// quick.Check generates random strings for deploymentName.
	// We filter out strings containing newlines since those would break the
	// single-line comment format (the spec requires a single comment line).
	prop := func(deploymentName string) bool {
		// Skip strings with newlines or carriage returns — they cannot appear
		// in a single-line nginx comment.
		if strings.ContainsAny(deploymentName, "\n\r") {
			return true // skip, not a valid deployment name
		}
		// Skip empty, all-whitespace, or untrimmed names since extractVesselDeployment
		// trims spaces and we only verify properties for trimmed names.
		if deploymentName == "" || strings.TrimSpace(deploymentName) != deploymentName {
			return true
		}

		counter++
		siteName := fmt.Sprintf("qs-site-%d", counter)

		if err := m.CreateSiteForDeployment(siteName, "test.example.com", 9090, "", deploymentName); err != nil {
			// File system error — not a property violation, but report it.
			t.Logf("CreateSiteForDeployment error (skipping): %v", err)
			return true
		}

		data, err := os.ReadFile(filepath.Join(sitesAvailable, siteName))
		if err != nil {
			t.Logf("ReadFile error (skipping): %v", err)
			return true
		}
		content := string(data)

		// First line must be exactly the comment.
		lines := strings.SplitN(content, "\n", 2)
		expectedFirstLine := "# vessel-deployment: " + deploymentName
		return lines[0] == expectedFirstLine
	}

	cfg := &quick.Config{MaxCount: 20}
	if err := quick.Check(prop, cfg); err != nil {
		t.Errorf("Property 13 (first line) violated: %v", err)
	}
	t.Logf("Property 13 (first line) verified across %d valid deployment names", counter)
}

// TestVesselDeploymentExtractRoundTripProperty uses testing/quick to verify
// that for any deployment name (generated by the quick framework),
// extractVesselDeployment is the left-inverse of the comment insertion
// performed by CreateSiteForDeployment.
//
// **Validates: Requirements 6.2, 6.3**
func TestVesselDeploymentExtractRoundTripProperty(t *testing.T) {
	tmpDir := t.TempDir()
	sitesAvailable := filepath.Join(tmpDir, "sites-available")
	if err := os.MkdirAll(sitesAvailable, 0755); err != nil {
		t.Fatalf("failed to create sites-available: %v", err)
	}
	m := &Manager{configRoot: tmpDir}

	counter := 0

	prop := func(deploymentName string) bool {
		// Skip strings with newlines — invalid in a single-line comment.
		if strings.ContainsAny(deploymentName, "\n\r") {
			return true
		}
		// Skip empty, all-whitespace, or untrimmed names since extractVesselDeployment
		// trims spaces and we only verify properties for trimmed names.
		if deploymentName == "" || strings.TrimSpace(deploymentName) != deploymentName {
			return true
		}

		counter++
		siteName := fmt.Sprintf("rt-site-%d", counter)

		if err := m.CreateSiteForDeployment(siteName, "rt.example.com", 7070, "", deploymentName); err != nil {
			t.Logf("CreateSiteForDeployment error (skipping): %v", err)
			return true
		}

		data, err := os.ReadFile(filepath.Join(sitesAvailable, siteName))
		if err != nil {
			t.Logf("ReadFile error (skipping): %v", err)
			return true
		}

		// Round-trip: extract must return the original name.
		extracted := extractVesselDeployment(string(data))
		return extracted == deploymentName
	}

	cfg := &quick.Config{MaxCount: 20}
	if err := quick.Check(prop, cfg); err != nil {
		t.Errorf("Property 13 (round-trip) violated: %v", err)
	}
	t.Logf("Property 13 (round-trip) verified across %d valid deployment names", counter)
}

// TestVesselDeploymentCommentSpecialCharacters verifies the round-trip
// property for a curated set of deployment names that include spaces,
// special characters, unicode, and edge cases.
//
// **Validates: Requirements 6.2, 6.3**
func TestVesselDeploymentCommentSpecialCharacters(t *testing.T) {
	specialNames := []string{
		"my-app",
		"my app",
		"my_app",
		"My App v2.0",
		"app with spaces and more spaces",
		"app!@#$%^&*()",
		"app+equals=sign",
		"app[brackets]",
		"app{braces}",
		"app|pipe",
		"app;semicolon",
		"app'quote",
		`app"doublequote`,
		"app,comma.period",
		"app<less>greater",
		"app?question/slash",
		"app~tilde`backtick",
		"123numeric456",
		"UPPERCASE",
		"MixedCase-App_v1.2.3",
		// Note: names with leading/trailing whitespace are intentionally
		// excluded here. extractVesselDeployment trims the extracted value,
		// so "  leading spaces" would extract as "leading spaces" — the
		// round-trip only holds for names that are already trimmed.
		"a", // single character
		strings.Repeat("x", 60), // long name
		"unicode-café",
		"日本語",
		"emoji-🚀",
	}

	tmpDir := t.TempDir()
	sitesAvailable := filepath.Join(tmpDir, "sites-available")
	if err := os.MkdirAll(sitesAvailable, 0755); err != nil {
		t.Fatalf("failed to create sites-available: %v", err)
	}
	m := &Manager{configRoot: tmpDir}

	for i, name := range specialNames {
		siteName := fmt.Sprintf("special-%d", i)

		err := m.CreateSiteForDeployment(siteName, "special.example.com", 8080, "", name)
		if err != nil {
			t.Errorf("name=%q: CreateSiteForDeployment error: %v", name, err)
			continue
		}

		data, err := os.ReadFile(filepath.Join(sitesAvailable, siteName))
		if err != nil {
			t.Errorf("name=%q: ReadFile error: %v", name, err)
			continue
		}
		content := string(data)

		// First line must be exactly the comment.
		expectedFirstLine := "# vessel-deployment: " + name
		lines := strings.SplitN(content, "\n", 2)
		if lines[0] != expectedFirstLine {
			t.Errorf("name=%q: first line = %q, want %q", name, lines[0], expectedFirstLine)
		}

		// Round-trip must be exact.
		extracted := extractVesselDeployment(content)
		if extracted != name {
			t.Errorf("name=%q: round-trip failed: extractVesselDeployment = %q", name, extracted)
		}
	}
}

// TestExtractVesselDeploymentNeverPanicsProperty verifies that
// extractVesselDeployment never panics on any string input, including
// strings with arbitrary unicode, null bytes, and control characters.
//
// **Validates: Requirements 6.2**
func TestExtractVesselDeploymentNeverPanicsProperty(t *testing.T) {
	prop := func(content string) bool {
		// Must not panic — just call it.
		_ = extractVesselDeployment(content)
		return true
	}
	cfg := &quick.Config{MaxCount: 20}
	if err := quick.Check(prop, cfg); err != nil {
		t.Errorf("extractVesselDeployment panicked on some input: %v", err)
	}
}

// TestExtractVesselDeploymentReturnTypeProperty verifies that
// extractVesselDeployment always returns a string (never panics, always
// returns a value that is either empty or a trimmed non-empty string).
//
// **Validates: Requirements 6.2**
func TestExtractVesselDeploymentReturnTypeProperty(t *testing.T) {
	rng := rand.New(rand.NewSource(99)) //nolint:gosec
	const iterations = 20

	for i := 0; i < iterations; i++ {
		// Generate a random content string.
		length := rng.Intn(200)
		var sb strings.Builder
		for j := 0; j < length; j++ {
			// Use printable ASCII plus newlines for realistic nginx config content.
			r := rune(32 + rng.Intn(95))
			if rng.Intn(20) == 0 {
				r = '\n'
			}
			sb.WriteRune(r)
		}
		content := sb.String()

		result := extractVesselDeployment(content)

		// Result must not have leading or trailing whitespace (it is trimmed).
		if result != strings.TrimSpace(result) {
			t.Errorf("iteration %d: extractVesselDeployment returned untrimmed result %q", i, result)
		}

		// Result must not contain newlines.
		if strings.ContainsAny(result, "\n\r") {
			t.Errorf("iteration %d: extractVesselDeployment returned result with newline: %q", i, result)
		}

		// If the content contains the prefix, the result must be non-empty
		// (unless the name part itself is all whitespace).
		prefix := "# vessel-deployment:"
		for _, line := range strings.Split(content, "\n") {
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, prefix) {
				namePart := strings.TrimSpace(strings.TrimPrefix(trimmed, prefix))
				if namePart != "" && result == "" {
					t.Errorf("iteration %d: content has prefix with non-empty name %q but extractVesselDeployment returned empty", i, namePart)
				}
				break
			}
		}

		// Result must not contain any control characters (except it may be empty).
		for _, r := range result {
			if unicode.IsControl(r) {
				t.Errorf("iteration %d: extractVesselDeployment returned result with control character U+%04X: %q", i, r, result)
				break
			}
		}
	}
}
